### ISSUE TITLE
Bump Tempo deps

### ISSUE THREAD

**Issue by andreapasquale94** [JuliaSpaceMissionDesign/IERS.jl#2]
https://github.com/JuliaSpaceMissionDesign/IERS.jl/blob/fd2ff8a84246f61cd65fbeaee00633128dfcc470/Project.toml#L10

This is a low-lever library, dependency from Tempo shall be removed.
Can be inserted in the `extras` as a test dependency.

**Comment by MicheleCeresoli** [comment]
Nono, this package is the one meant to implement within Tempo the actual UTC/TT to UT1 conversion! 
Plus, there are a number of other constants that would be required nonetheless when parsing the EOP data.

**Comment by andreapasquale94** [comment]
Yes agreed, I was reviewing the current content and I saw `sidereal.jl` as the only "coupling" location, but the EOP part, once implemented, would require some time transformations.
