### ISSUE TITLE
Arcsecond to rad function

### ISSUE THREAD

**Issue by andreapasquale94** [JuliaSpaceMissionDesign/IERS.jl#4]
https://github.com/JuliaSpaceMissionDesign/IERS.jl/blob/fd2ff8a84246f61cd65fbeaee00633128dfcc470/src/angles.jl#L2

Why this function is defined at this level? Shall be imported from `JSMDUtils.Math`.

**Comment by MicheleCeresoli** [comment]
Since that is literally the only one function that is required from JSMDUtils, it did not make much sense to me to introduce all of that package dependencies just for that super simple operation.

**Comment by andreapasquale94** [comment]
Ok perfect, this was just to double-check if there were any additional "hidden" dep to `JSMDUtils.jl`.
